# Generated by Django 2.0 on 2019-01-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='exhibition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='rules',
            field=models.CharField(choices=[('C', 'Competitive'), ('M', 'Mystery heroes')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='hero',
            name='hero_type',
            field=models.CharField(choices=[('D', 'Damage'), ('T', 'Tank'), ('S', 'Support')], max_length=1),
        ),
    ]
