# Generated by Django 2.0 on 2019-01-19 02:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190103_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'statuses',
            },
        ),
        migrations.CreateModel(
            name='StatusEffect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(decimal_places=1, max_digits=6)),
                ('end_time', models.DecimalField(decimal_places=1, max_digits=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Status')),
            ],
            options={
                'ordering': ['round', 'start_time', 'player'],
            },
        ),
        migrations.CreateModel(
            name='UltDenial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DecimalField(decimal_places=1, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='UltEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DecimalField(decimal_places=1, max_digits=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round')),
            ],
            options={
                'ordering': ['round', 'time_point', 'player'],
            },
        ),
        migrations.AlterModelOptions(
            name='ability',
            options={'ordering': ['name'], 'verbose_name_plural': 'abilities'},
        ),
        migrations.RemoveField(
            model_name='ability',
            name='hero',
        ),
        migrations.AddField(
            model_name='ability',
            name='heroes',
            field=models.ManyToManyField(to='api.Hero'),
        ),
        migrations.AddField(
            model_name='ability',
            name='matrixable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ultdenial',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ability'),
        ),
        migrations.AddField(
            model_name='ultdenial',
            name='denying_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ult_denials', to='api.Player'),
        ),
        migrations.AddField(
            model_name='ultdenial',
            name='eaten_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='denied_ults', to='api.Player'),
        ),
        migrations.AddField(
            model_name='ultdenial',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round'),
        ),
        migrations.AlterUniqueTogether(
            name='ultend',
            unique_together={('round', 'time_point', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='statuseffect',
            unique_together={('round', 'start_time', 'player', 'status')},
        ),
    ]
