# Generated by Django 2.0 on 2019-01-22 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190118_2113'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['hero_type', 'name'], 'verbose_name_plural': 'heroes'},
        ),
        migrations.AlterField(
            model_name='ability',
            name='heroes',
            field=models.ManyToManyField(related_name='abilities', to='api.Hero'),
        ),
        migrations.AlterField(
            model_name='event',
            name='spectator_mode',
            field=models.CharField(choices=[('C', 'Color'), ('W', 'World Cup'), ('L', 'Overwatch League'), ('A', 'Ability'), ('S', 'Status'), ('N', 'Contenders'), ('H', 'China Contenders'), ('K', 'Korea Contenders'), ('O', 'Original')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AddField(
            model_name='eventparticipation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
        migrations.AddField(
            model_name='event',
            name='teams',
            field=models.ManyToManyField(through='api.EventParticipation', to='api.Team'),
        ),
    ]
