# Generated by Django 2.0 on 2019-01-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190122_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['game__match__id', 'game__game_number', 'round_number']},
        ),
        migrations.AddField(
            model_name='event',
            name='stream_channels',
            field=models.ManyToManyField(related_name='events', to='api.StreamChannel'),
        ),
        migrations.AlterField(
            model_name='streamvod',
            name='status',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('G', 'Automatically annotated for in-game/out-of-game'), ('A', 'Rounds automatically annotated'), ('T', 'Game boundaries manually checked'), ('M', 'Round events manually corrected')], default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='streamvod',
            name='type',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('G', 'Automatically annotated for in-game/out-of-game'), ('A', 'Rounds automatically annotated'), ('T', 'Game boundaries manually checked'), ('M', 'Round events manually corrected')], default='G', max_length=1),
        ),
    ]
