# Generated by Django 2.0 on 2019-01-25 05:33

from django.db import migrations

def make_many_channels(apps, schema_editor):
    """
        Adds the Author object in Book.author to the
        many-to-many relationship in Book.authors
    """
    Event = apps.get_model('api', 'Event')

    for event in Event.objects.all():
        if event.channel is None:
            continue
        event.stream_channels.add(event.channel)

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190125_0033'),
    ]

    operations = [
        migrations.RunPython(make_many_channels),
    ]
