# Generated by Django 2.0 on 2019-01-25 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190125_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='channel',
        ),
    ]
