# Generated by Django 2.0 on 2019-01-28 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_streamchannel_youtube_channel_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ultdenial',
            old_name='eaten_player',
            new_name='denied_player',
        ),
    ]
