# Generated by Django 2.0 on 2019-07-26 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190217_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='channel_query_string',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='teamparticipation',
            name='color',
            field=models.CharField(choices=[('B', 'Blue'), ('R', 'Red'), ('W', 'White'), ('G', 'Green'), ('O', 'Orange'), ('Y', 'Yellow'), ('P', 'Purple'), ('I', 'Pink'), ('K', 'Black')], default='B', max_length=1),
        ),
    ]
