# Generated by Django 2.2.3 on 2019-08-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190725_2217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['-match__id', 'game_number']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-id'], 'verbose_name_plural': 'matches'},
        ),
        migrations.AddField(
            model_name='ability',
            name='denyable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ability',
            name='denying_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='spectator_mode',
            field=models.CharField(choices=[('O', 'Original'), ('W', 'World Cup'), ('L', 'Overwatch League'), ('C', 'Contenders')], default='S', max_length=1),
        ),
        migrations.AlterField(
            model_name='streamvod',
            name='status',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('G', 'Automatically annotated for in-game/out-of-game'), ('T', 'Game boundaries manually checked'), ('A', 'Rounds automatically annotated'), ('M', 'Round events manually corrected')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='streamvod',
            name='type',
            field=models.CharField(choices=[('M', 'Match'), ('G', 'Game'), ('R', 'Round')], default='M', max_length=1),
        ),
    ]
