# Generated by Django 2.2.3 on 2019-08-17 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190817_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='denyable',
            new_name='deniable',
        ),
    ]
