# Generated by Django 2.2.3 on 2019-08-18 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190817_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ability',
            name='matrixable',
        ),
    ]
