# Generated by Django 2.2.3 on 2019-08-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_ability_matrixable'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='film_format',
            field=models.CharField(choices=[('O', 'Original'), ('W', 'World Cup 2017'), ('A', 'APEX'), ('K', 'Korean Contenders'), ('2', 'Overwatch league season 2')], default='O', max_length=1),
        ),
    ]
