# Generated by Django 2.2.3 on 2019-08-30 19:51

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_event_film_format'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6)),
                ('end_time', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('N', 'Neither')], default='N', max_length=1)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round')),
            ],
            options={
                'ordering': ['round', 'start_time', 'side'],
                'unique_together': {('round', 'start_time', 'side')},
            },
        ),
    ]
