# Generated by Django 2.2.3 on 2019-08-31 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_zoom'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Switch',
            new_name='HeroPick',
        ),
        migrations.AlterField(
            model_name='kill',
            name='assisting_players',
            field=models.ManyToManyField(related_name='assists', to='api.Player'),
        ),
        migrations.AlterField(
            model_name='kill',
            name='killing_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kill_kills', to='api.Player'),
        ),
        migrations.CreateModel(
            name='Ultimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gained_at', models.DecimalField(decimal_places=1, max_digits=6)),
                ('used_at', models.DecimalField(decimal_places=1, max_digits=6)),
                ('ended_at', models.DecimalField(decimal_places=1, max_digits=6)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round')),
            ],
        ),
        migrations.CreateModel(
            name='KillFeedEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DecimalField(decimal_places=1, max_digits=6)),
                ('headshot', models.BooleanField(default=False)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Ability')),
                ('assisting_players', models.ManyToManyField(related_name='assisted_kills', to='api.Player')),
                ('dying_npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.NPC')),
                ('dying_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deaths', to='api.Player')),
                ('killing_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='api.Player')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round')),
            ],
            options={
                'ordering': ['round', 'time_point', 'killing_player', 'dying_player'],
                'unique_together': {('round', 'time_point', 'dying_player')},
            },
        ),
    ]
