# Generated by Django 2.2.3 on 2019-08-31 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_killfeedevent_denied_ult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killfeedevent',
            name='ability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Ability'),
        ),
    ]
