# Generated by Django 2.2.3 on 2019-08-31 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20190831_1710'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='killfeedevent',
            unique_together={('round', 'time_point', 'killing_player', 'dying_player')},
        ),
    ]
