# Generated by Django 2.2.3 on 2019-09-01 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_auto_20190831_1725'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='killfeedevent',
            unique_together={('round', 'time_point', 'killing_player', 'dying_player', 'dying_npc', 'denied_ult')},
        ),
    ]
