# Generated by Django 2.2.3 on 2019-09-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_auto_20190831_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ultimate',
            options={'ordering': ['round', 'gained_at', 'player']},
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='ended_at',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='ultimate',
            name='used_at',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
