# Generated by Django 2.2.3 on 2019-09-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20190901_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ability',
            old_name='ultimate_ability',
            new_name='ultimate',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='damaging_ability',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='denying_ability',
        ),
        migrations.RemoveField(
            model_name='ability',
            name='revive_ability',
        ),
        migrations.AddField(
            model_name='ability',
            name='type',
            field=models.CharField(choices=[('D', 'Damaging'), ('R', 'Reviving'), ('E', 'Denying')], default='D', max_length=1),
        ),
    ]
