# Generated by Django 2.2.3 on 2019-09-01 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_auto_20190901_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['type', 'name'], 'verbose_name_plural': 'heroes'},
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='hero_type',
            new_name='type',
        ),
    ]
