# Generated by Django 2.2.3 on 2019-09-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20190901_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='independent',
            field=models.BooleanField(default=False),
        ),
    ]
