# Generated by Django 2.2.3 on 2019-09-01 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_status_independent'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='causing_hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Hero'),
        ),
    ]
