# Generated by Django 2.2.3 on 2019-09-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_status_causing_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='helpful',
            field=models.BooleanField(default=False),
        ),
    ]
