# Generated by Django 2.2.3 on 2019-09-03 15:35

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_status_helpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='ult_duration',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=6),
        ),
    ]
