# Generated by Django 2.2.3 on 2019-09-08 18:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_auto_20190905_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='default_duration',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=6),
        ),
    ]
