# Generated by Django 2.2.6 on 2019-11-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20191104_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killfeedevent',
            name='assisting_players',
        ),
        migrations.AlterField(
            model_name='streamvod',
            name='film_format',
            field=models.CharField(choices=[('O', 'Original'), ('W', 'World Cup 2017'), ('A', 'APEX'), ('1', 'Korean Contenders season 1'), ('K', 'Korean Contenders season 2'), ('U', 'Australia Contenders season 2'), ('2', 'Overwatch league season 2')], default='O', max_length=1),
        ),
    ]
