# Generated by Django 2.2.6 on 2020-01-07 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_auto_20191222_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='exclude_for_training',
            field=models.BooleanField(default=False),
        ),
    ]
