# Generated by Django 2.2.6 on 2020-01-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_round_exclude_for_training'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='film_format',
            field=models.CharField(choices=[('O', 'Original'), ('W', 'World Cup 2017'), ('A', 'APEX'), ('1', 'Korean Contenders season 1'), ('K', 'Korean Contenders season 2'), ('U', 'Australia Contenders season 2'), ('G', 'Gauntlet 2019'), ('2', 'Overwatch league season 2')], default='O', max_length=1),
        ),
    ]
