# Generated by Django 2.2.6 on 2020-01-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_auto_20200116_0228'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='icon_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
