# Generated by Django 2.2.6 on 2020-01-24 15:55

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_status_icon_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilmFormat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='PauseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ReplayType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SmallerWindowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='SpectatorMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=128)),
                ('home_color', colorful.fields.RGBColorField(blank=True, null=True)),
                ('away_color', colorful.fields.RGBColorField(blank=True, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='event',
            old_name='film_format',
            new_name='film_format_old',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='spectator_mode',
            new_name='spectator_mode_old',
        ),
        migrations.RenameField(
            model_name='streamvod',
            old_name='film_format',
            new_name='film_format_old',
        ),
        migrations.AddField(
            model_name='pause',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.PauseType'),
        ),
        migrations.AddField(
            model_name='replay',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ReplayType'),
        ),
        migrations.AddField(
            model_name='smallerwindow',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SmallerWindowType'),
        ),
    ]
