# Generated by Django 2.2.6 on 2020-01-24 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_auto_20200124_0855'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='film_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FilmFormat'),
        ),
        migrations.AddField(
            model_name='event',
            name='spectator_mode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.SpectatorMode'),
        ),
        migrations.AddField(
            model_name='streamvod',
            name='film_format',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.FilmFormat'),
        ),
    ]
