# Generated by Django 2.2.6 on 2020-01-25 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_auto_20200124_0859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='film_format_old',
        ),
        migrations.RemoveField(
            model_name='event',
            name='spectator_mode_old',
        ),
        migrations.RemoveField(
            model_name='streamvod',
            name='film_format_old',
        ),
    ]
