# Generated by Django 2.2.6 on 2020-01-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_auto_20200125_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='spectatormode',
            name='uses_team_colors',
            field=models.BooleanField(default=False),
        ),
    ]
