# Generated by Django 2.2.6 on 2020-02-06 23:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_spectatormode_uses_team_colors'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamFight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DecimalField(decimal_places=1, max_digits=6)),
                ('end_time', models.DecimalField(decimal_places=1, max_digits=6)),
                ('attacking_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attacking_team', to='api.TeamParticipation')),
                ('defending_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defending_team', to='api.TeamParticipation')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Round')),
            ],
        ),
    ]
