# Generated by Django 2.2.6 on 2020-02-08 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_teamfight'),
    ]

    operations = [
        migrations.AddField(
            model_name='killfeedevent',
            name='environmental',
            field=models.BooleanField(default=False),
        ),
    ]
