# Generated by Django 2.2.6 on 2020-02-18 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_killfeedevent_environmental'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teamfight',
            name='attacking_team',
        ),
        migrations.RemoveField(
            model_name='teamfight',
            name='defending_team',
        ),
    ]
