# Generated by Django 2.2.6 on 2020-03-03 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_auto_20200217_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamvod',
            name='type',
            field=models.CharField(choices=[('M', 'Match'), ('S', 'Multiple matches'), ('G', 'Game'), ('R', 'Round')], default='M', max_length=1),
        ),
    ]
