# Generated by Django 2.0 on 2017-12-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ability',
            options={'verbose_name_plural': 'abilities'},
        ),
        migrations.AddField(
            model_name='map',
            name='mode',
            field=models.CharField(choices=[('A', 'Assault'), ('E', 'Escort'), ('C', 'Control'), ('H', 'Hybrid')], default='', max_length=1),
            preserve_default=False,
        ),
    ]
