# Generated by Django 2.0 on 2017-12-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0004_auto_20171208_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'verbose_name_plural': 'heroes'},
        ),
        migrations.AddField(
            model_name='ability',
            name='ultimate_ability',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ability',
            name='headshot_capable',
            field=models.BooleanField(default=False),
        ),
    ]
