# Generated by Django 2.0 on 2017-12-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0006_auto_20171208_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='left_subpoints',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='game',
            name='right_subpoints',
            field=models.CharField(max_length=128),
        ),
    ]
