# Generated by Django 2.0 on 2017-12-10 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0007_auto_20171209_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillNPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.IntegerField()),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Ability')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_index', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Player')),
            ],
            options={
                'ordering': ['player_index'],
            },
        ),
        migrations.CreateModel(
            name='TeamParticipation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('B', 'Blue'), ('R', 'Red'), ('W', 'White'), ('G', 'Green'), ('O', 'Orange'), ('Y', 'Yellow'), ('P', 'Purple'), ('K', 'Black')], default='B', max_length=1)),
                ('side', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('N', 'Neither')], default='N', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='participation',
            name='game',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='players',
        ),
        migrations.RemoveField(
            model_name='participation',
            name='team',
        ),
        migrations.AddField(
            model_name='game',
            name='local_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='game',
            name='vod',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kill',
            name='headshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='match',
            name='local_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='vod',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='begin',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='round',
            name='local_location',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='vod',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(through='annotator.TeamParticipation', to='annotator.Team'),
        ),
        migrations.AlterField(
            model_name='hero',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='map',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='npc',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('match', 'game_number')},
        ),
        migrations.AlterUniqueTogether(
            name='round',
            unique_together={('game', 'round_number')},
        ),
        migrations.DeleteModel(
            name='Participation',
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Game'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='players',
            field=models.ManyToManyField(through='annotator.PlayerParticipation', to='annotator.Player'),
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Team'),
        ),
        migrations.AddField(
            model_name='playerparticipation',
            name='team_participation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.TeamParticipation'),
        ),
        migrations.AddField(
            model_name='killnpc',
            name='killed_npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killed_npc', to='annotator.NPC'),
        ),
        migrations.AddField(
            model_name='killnpc',
            name='killing_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_killing_player', to='annotator.Player'),
        ),
        migrations.AddField(
            model_name='killnpc',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Round'),
        ),
        migrations.AlterUniqueTogether(
            name='playerparticipation',
            unique_together={('team_participation', 'player_index')},
        ),
    ]
