# Generated by Django 2.0 on 2017-12-10 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0008_auto_20171209_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='wl_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='wl_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='wl_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='wl_id',
        ),
    ]
