# Generated by Django 2.0 on 2017-12-12 04:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0009_auto_20171210_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='switch',
            name='new_hero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='annotator.Hero'),
        ),
    ]
