# Generated by Django 2.0 on 2017-12-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0010_auto_20171211_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='wl_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='wl_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='wl_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='team',
            name='wl_id',
            field=models.IntegerField(null=True),
        ),
    ]
