# Generated by Django 2.0 on 2017-12-13 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0011_auto_20171212_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='wl_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='wl_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='wl_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='wl_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
