# Generated by Django 2.0 on 2017-12-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0012_auto_20171212_1909'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='death',
            unique_together={('round', 'time_point', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='kill',
            unique_together={('round', 'time_point', 'killing_player', 'killed_player')},
        ),
        migrations.AlterUniqueTogether(
            name='killnpc',
            unique_together={('round', 'time_point', 'killing_player', 'killed_npc')},
        ),
        migrations.AlterUniqueTogether(
            name='npcdeath',
            unique_together={('round', 'time_point', 'npc', 'side')},
        ),
        migrations.AlterUniqueTogether(
            name='pause',
            unique_together={('round', 'time_point')},
        ),
        migrations.AlterUniqueTogether(
            name='pointflip',
            unique_together={('round', 'time_point')},
        ),
        migrations.AlterUniqueTogether(
            name='pointgain',
            unique_together={('round', 'time_point')},
        ),
        migrations.AlterUniqueTogether(
            name='revive',
            unique_together={('round', 'time_point', 'reviving_player', 'revived_player')},
        ),
        migrations.AlterUniqueTogether(
            name='switch',
            unique_together={('round', 'time_point', 'player', 'new_hero')},
        ),
        migrations.AlterUniqueTogether(
            name='ultgain',
            unique_together={('round', 'time_point', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='ultuse',
            unique_together={('round', 'time_point', 'player')},
        ),
        migrations.AlterUniqueTogether(
            name='unpause',
            unique_together={('round', 'time_point')},
        ),
    ]
