# Generated by Django 2.0 on 2017-12-15 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0013_auto_20171212_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='death',
            options={'ordering': ['round', 'time_point', 'player']},
        ),
        migrations.AlterModelOptions(
            name='kill',
            options={'ordering': ['round', 'time_point', 'killing_player', 'killed_player']},
        ),
        migrations.AlterModelOptions(
            name='killnpc',
            options={'ordering': ['round', 'time_point', 'killing_player', 'killed_npc']},
        ),
        migrations.AlterModelOptions(
            name='npcdeath',
            options={'ordering': ['round', 'time_point', 'side', 'npc']},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['name', 'wl_id']},
        ),
        migrations.AlterModelOptions(
            name='revive',
            options={'ordering': ['round', 'time_point', 'reviving_player', 'revived_player']},
        ),
        migrations.AlterModelOptions(
            name='switch',
            options={'ordering': ['round', 'time_point', 'player']},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['name', 'wl_id']},
        ),
        migrations.AlterModelOptions(
            name='teamparticipation',
            options={'ordering': ['side']},
        ),
        migrations.AlterModelOptions(
            name='ultgain',
            options={'ordering': ['round', 'time_point', 'player']},
        ),
        migrations.AlterModelOptions(
            name='ultuse',
            options={'ordering': ['round', 'time_point', 'player']},
        ),
        migrations.AlterUniqueTogether(
            name='teamparticipation',
            unique_together={('game', 'side')},
        ),
    ]
