# Generated by Django 2.0 on 2017-12-17 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0014_auto_20171214_2036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='left_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='left_subpoints',
        ),
        migrations.RemoveField(
            model_name='game',
            name='right_points',
        ),
        migrations.RemoveField(
            model_name='game',
            name='right_subpoints',
        ),
        migrations.RemoveField(
            model_name='game',
            name='teams',
        ),
        migrations.AddField(
            model_name='game',
            name='left_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='left_team', to='annotator.TeamParticipation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='right_team',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='right_team', to='annotator.TeamParticipation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teamparticipation',
            name='subpoints',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
