# Generated by Django 2.0 on 2017-12-17 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0015_auto_20171217_1444'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teamparticipation',
            options={'ordering': ['points', 'subpoints']},
        ),
        migrations.AlterField(
            model_name='game',
            name='left_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='left_team', to='annotator.TeamParticipation'),
        ),
        migrations.AlterField(
            model_name='game',
            name='right_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='right_team', to='annotator.TeamParticipation'),
        ),
        migrations.AlterUniqueTogether(
            name='teamparticipation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='teamparticipation',
            name='game',
        ),
        migrations.RemoveField(
            model_name='teamparticipation',
            name='side',
        ),
    ]
