# Generated by Django 2.0 on 2017-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0016_auto_20171217_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamparticipation',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamparticipation',
            name='subpoints',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
