# Generated by Django 2.0 on 2017-12-28 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0019_auto_20171225_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='wl_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='wl_id',
            field=models.IntegerField(null=True),
        ),
    ]
