# Generated by Django 2.0 on 2017-12-28 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0020_auto_20171228_1251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='local_location',
        ),
        migrations.RemoveField(
            model_name='match',
            name='local_location',
        ),
        migrations.RemoveField(
            model_name='round',
            name='local_location',
        ),
    ]
