# Generated by Django 2.0 on 2017-12-29 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0021_auto_20171228_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='film_format',
            field=models.CharField(choices=[('R', 'Regular'), ('A', 'APEX')], default='R', max_length=1),
        ),
    ]
