# Generated by Django 2.0 on 2017-12-29 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0022_event_film_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='local_status',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('V', 'Video exported'), ('E', 'Error in processing')], default='N', max_length=1),
        ),
    ]
