# Generated by Django 2.0 on 2017-12-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0023_round_local_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='annotation_status',
            field=models.CharField(choices=[('N', 'None'), ('W', "Winston's lab"), ('M', 'Manual'), ('O', 'Ominc intelligence')], default='N', max_length=1),
        ),
    ]
