# Generated by Django 2.0 on 2017-12-30 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0024_round_annotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='local_status',
        ),
    ]
