# Generated by Django 2.0 on 2017-12-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0025_remove_round_local_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='annotation_export_status',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('S', 'Successfully exported'), ('E', 'Error in processing')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='round',
            name='video_status',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('S', 'Successfully exported'), ('E', 'Error in processing')], default='N', max_length=1),
        ),
    ]
