# Generated by Django 2.0 on 2017-12-31 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0026_auto_20171231_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='video_status',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('L', 'Lacking video file'), ('S', 'Successfully exported'), ('E', 'Error in processing')], default='N', max_length=1),
        ),
    ]
