# Generated by Django 2.0 on 2018-01-02 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0027_auto_20171231_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='OvertimeEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.IntegerField()),
            ],
            options={
                'ordering': ['round', 'time_point'],
            },
        ),
        migrations.AlterModelOptions(
            name='game',
            options={'ordering': ['game_number']},
        ),
        migrations.AlterModelOptions(
            name='overtimestart',
            options={'ordering': ['round', 'time_point']},
        ),
        migrations.AlterModelOptions(
            name='pause',
            options={'ordering': ['round', 'time_point']},
        ),
        migrations.AlterModelOptions(
            name='pointflip',
            options={'ordering': ['round', 'time_point']},
        ),
        migrations.AlterModelOptions(
            name='pointgain',
            options={'ordering': ['round', 'time_point']},
        ),
        migrations.AlterModelOptions(
            name='replayend',
            options={'ordering': ['round', 'time_point']},
        ),
        migrations.AlterModelOptions(
            name='replaystart',
            options={'ordering': ['round', 'time_point']},
        ),
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['round_number']},
        ),
        migrations.AlterModelOptions(
            name='unpause',
            options={'ordering': ['round', 'time_point']},
        ),
        migrations.AlterField(
            model_name='round',
            name='annotation_status',
            field=models.CharField(choices=[('N', 'None'), ('W', "Winston's lab"), ('M', 'Manual'), ('O', 'Omnic intelligence')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='overtimeend',
            name='round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Round'),
        ),
        migrations.AlterUniqueTogether(
            name='overtimeend',
            unique_together={('round', 'time_point')},
        ),
    ]
