# Generated by Django 2.0 on 2018-01-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0028_auto_20180101_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='spectator_mode',
            field=models.CharField(choices=[('C', 'Color'), ('A', 'Ability'), ('O', 'Original')], default='A', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='round',
            name='video_status',
            field=models.CharField(choices=[('N', 'Not analyzed'), ('L', 'Local file available'), ('S', 'Successfully exported'), ('E', 'Error in processing')], default='N', max_length=1),
        ),
    ]
