# Generated by Django 2.0 on 2018-01-11 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0030_auto_20180111_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='spectator_mode',
        ),
        migrations.AddField(
            model_name='match',
            name='spectator_mode',
            field=models.CharField(choices=[('C', 'Color'), ('A', 'Ability'), ('O', 'Original')], default='A', max_length=1),
            preserve_default=False,
        ),
    ]
