# Generated by Django 2.0 on 2018-01-12 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0032_auto_20180111_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='death',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='kill',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='killnpc',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='npcdeath',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='overtimeend',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='overtimestart',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pause',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pointflip',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pointgain',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='replayend',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='replaystart',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='revive',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='switch',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ultgain',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ultuse',
            name='time_point',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='unpause',
            name='time_point',
            field=models.FloatField(),
        ),
    ]
