# Generated by Django 2.0 on 2018-01-19 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0034_auto_20180118_1315'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['wl_id']},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['wl_id'], 'verbose_name_plural': 'matches'},
        ),
        migrations.RemoveField(
            model_name='round',
            name='annotation_export_status',
        ),
        migrations.RemoveField(
            model_name='round',
            name='video_status',
        ),
    ]
