# Generated by Django 2.0 on 2018-02-09 01:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0035_auto_20180119_0153'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillAssist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Player')),
                ('kill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Kill')),
            ],
        ),
        migrations.CreateModel(
            name='KillNPCAssist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assisting_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Player')),
                ('kill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.KillNPC')),
            ],
        ),
        migrations.AlterField(
            model_name='match',
            name='spectator_mode',
            field=models.CharField(choices=[('C', 'Color'), ('W', 'World Cup'), ('L', 'Overwatch League'), ('A', 'Ability'), ('O', 'Original')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='round',
            name='begin',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6),
        ),
        migrations.AlterField(
            model_name='round',
            name='end',
            field=models.DecimalField(decimal_places=1, default=Decimal('0.0'), max_digits=6),
        ),
    ]
