# Generated by Django 2.0 on 2018-02-10 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0037_auto_20180208_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='killassist',
            name='assisting_player',
        ),
        migrations.RemoveField(
            model_name='killassist',
            name='kill',
        ),
        migrations.RemoveField(
            model_name='killnpcassist',
            name='assisting_player',
        ),
        migrations.RemoveField(
            model_name='killnpcassist',
            name='kill',
        ),
        migrations.AddField(
            model_name='kill',
            name='assisting_players',
            field=models.ManyToManyField(related_name='assisted_kills', to='annotator.Player'),
        ),
        migrations.AddField(
            model_name='killnpc',
            name='assisting_players',
            field=models.ManyToManyField(related_name='assisted_npc_kills', to='annotator.Player'),
        ),
        migrations.AlterField(
            model_name='kill',
            name='killed_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killeds', to='annotator.Player'),
        ),
        migrations.AlterField(
            model_name='kill',
            name='killing_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kills', to='annotator.Player'),
        ),
        migrations.AlterField(
            model_name='killnpc',
            name='killed_npc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='killeds', to='annotator.NPC'),
        ),
        migrations.AlterField(
            model_name='killnpc',
            name='killing_player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_kills', to='annotator.Player'),
        ),
        migrations.DeleteModel(
            name='KillAssist',
        ),
        migrations.DeleteModel(
            name='KillNPCAssist',
        ),
    ]
