# Generated by Django 2.0 on 2018-02-17 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0038_auto_20180209_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='spectator_mode',
        ),
        migrations.AddField(
            model_name='event',
            name='spectator_mode',
            field=models.CharField(choices=[('C', 'Color'), ('W', 'World Cup'), ('L', 'Overwatch League'), ('A', 'Ability'), ('O', 'Original')], default='C', max_length=1),
        ),
    ]
