# Generated by Django 2.0 on 2018-02-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0039_auto_20180217_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='film_format',
        ),
        migrations.AddField(
            model_name='match',
            name='film_format',
            field=models.CharField(choices=[('O', 'Original'), ('A', 'APEX'), ('2', 'Overwatch league stage 2')], default='O', max_length=1),
        ),
    ]
