# Generated by Django 2.0 on 2018-02-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0040_auto_20180225_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='film_format',
            field=models.CharField(choices=[('O', 'Original'), ('W', 'World Cup 2017'), ('A', 'APEX'), ('2', 'Overwatch league stage 2')], default='O', max_length=1),
        ),
    ]
