# Generated by Django 2.0 on 2018-03-12 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0041_auto_20180226_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediumWindowEnd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DecimalField(decimal_places=1, max_digits=6)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Round')),
            ],
            options={
                'ordering': ['round', 'time_point'],
            },
        ),
        migrations.CreateModel(
            name='MediumWindowStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_point', models.DecimalField(decimal_places=1, max_digits=6)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.Round')),
            ],
            options={
                'ordering': ['round', 'time_point'],
            },
        ),
        migrations.CreateModel(
            name='StreamChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
                ('site', models.CharField(choices=[('T', 'Twitch'), ('Y', 'YouTube')], default='T', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='StreamVod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=256, unique=True)),
                ('broadcast_date', models.DateField(blank=True, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annotator.StreamChannel')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.StreamChannel'),
        ),
        migrations.AddField(
            model_name='round',
            name='stream_vod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='annotator.StreamVod'),
        ),
        migrations.AlterUniqueTogether(
            name='mediumwindowstart',
            unique_together={('round', 'time_point')},
        ),
        migrations.AlterUniqueTogether(
            name='mediumwindowend',
            unique_together={('round', 'time_point')},
        ),
    ]
