# Generated by Django 2.0 on 2018-03-14 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0042_auto_20180311_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamvod',
            name='title',
            field=models.CharField(default='', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
