# Generated by Django 2.0 on 2018-03-14 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0043_streamvod_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streamvod',
            name='broadcast_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
