# Generated by Django 2.0 on 2018-03-21 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0045_auto_20180313_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='streamvod',
            name='film_format',
            field=models.CharField(choices=[('O', 'Original'), ('W', 'World Cup 2017'), ('A', 'APEX'), ('2', 'Overwatch league stage 2')], default='O', max_length=1),
        ),
    ]
