# Generated by Django 2.0 on 2018-03-21 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0046_streamvod_film_format'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='vod',
        ),
        migrations.RemoveField(
            model_name='match',
            name='film_format',
        ),
        migrations.RemoveField(
            model_name='match',
            name='vod',
        ),
        migrations.RemoveField(
            model_name='round',
            name='vod',
        ),
    ]
