# Generated by Django 2.0 on 2018-03-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0047_auto_20180321_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='description',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
