# Generated by Django 2.0 on 2018-03-30 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0048_match_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='wl_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='event',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='annotator.Event'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='wl_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='wl_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='streamvod',
            name='film_format',
            field=models.CharField(choices=[('O', 'Original'), ('W', 'World Cup 2017'), ('A', 'APEX'), ('K', 'Korean Contenders'), ('2', 'Overwatch league stage 2')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='wl_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
