# Generated by Django 2.0 on 2018-04-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0049_auto_20180330_1959'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MediumWindowEnd',
            new_name='SmallerWindowEnd',
        ),
        migrations.RenameModel(
            old_name='MediumWindowStart',
            new_name='SmallerWindowStart',
        ),
        migrations.AlterField(
            model_name='event',
            name='spectator_mode',
            field=models.CharField(choices=[('C', 'Color'), ('W', 'World Cup'), ('L', 'Overwatch League'), ('A', 'Ability'), ('N', 'Contenders'), ('H', 'China Contenders'), ('K', 'Korea Contenders'), ('O', 'Original')], default='C', max_length=1),
        ),
    ]
