# Generated by Django 2.0 on 2018-04-16 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annotator', '0050_auto_20180413_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='end_time_point',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
    ]
